// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPDIHCrAvNSCV29wPIoIa9ib4j6yuY3Vc',
    appId: '1:74904678492:web:e96c49ca2c4bda9d3ff699',
    messagingSenderId: '74904678492',
    projectId: 'juancx-9e024',
    authDomain: 'juancx-9e024.firebaseapp.com',
    storageBucket: 'juancx-9e024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IVFBZtO0KHeHaH5SHQut_SMRS4fV2HU',
    appId: '1:74904678492:android:4d9389409074d3263ff699',
    messagingSenderId: '74904678492',
    projectId: 'juancx-9e024',
    storageBucket: 'juancx-9e024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAagLBQdOSd3WSVOYOquw_G2IppFCAiVg',
    appId: '1:74904678492:ios:891ded53d3c64c863ff699',
    messagingSenderId: '74904678492',
    projectId: 'juancx-9e024',
    storageBucket: 'juancx-9e024.firebasestorage.app',
    iosBundleId: 'online.juancx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAagLBQdOSd3WSVOYOquw_G2IppFCAiVg',
    appId: '1:74904678492:ios:891ded53d3c64c863ff699',
    messagingSenderId: '74904678492',
    projectId: 'juancx-9e024',
    storageBucket: 'juancx-9e024.firebasestorage.app',
    iosBundleId: 'online.juancx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPDIHCrAvNSCV29wPIoIa9ib4j6yuY3Vc',
    appId: '1:74904678492:web:e91a693cfbc485413ff699',
    messagingSenderId: '74904678492',
    projectId: 'juancx-9e024',
    authDomain: 'juancx-9e024.firebaseapp.com',
    storageBucket: 'juancx-9e024.firebasestorage.app',
  );
}
